image:
  file: .gitpod.dockerfile

tasks:
  - name: Install And Run
    before: |
      npm install -g gulp-cli
    init: |
      mysql -u root -e "create database osm"
      bin/create-env.sh
      sed -i "s|MYSQL_USERNAME=\\.\\.\\.|MYSQL_USERNAME=root|g" .env.Osm_App
      sed -i "s|MYSQL_PASSWORD=\\.\\.\\.|MYSQL_PASSWORD=|g" .env.Osm_App
      sed -i "s|NAME=\\.\\.\\.|NAME=osm|g" .env.Osm_App
      bin/install.sh
      echo "alias osmc='php vendor/osmphp/core/bin/compile.php'"  >> "~/.bashrc" 
      echo "alias osmh='php vendor/osmphp/core/bin/hint.php'"  >> "~/.bashrc" 
      echo "alias osmt='php vendor/osmphp/framework/bin/tools.php'"  >> "~/.bashrc" 
      echo "alias osm='php vendor/osmphp/framework/bin/console.php'"  >> "~/.bashrc"
      php vendor/osmphp/core/bin/hint.php
    command: |
      sudo service elasticsearch start
      php -S 0.0.0.0:8000 -t public/Osm_App public/Osm_App/router.php

ports:
  - name: Web App
    port: 8000
    onOpen: open-browser

jetbrains:
  phpstorm:
    prebuilds:
      version: stable